w3c/wpt-tools

manifest/update.py
manifest/vcs.py

Also allow it to be overridden explicitly.

Fix the heuritsic for finding the tests root now we are in a submodule.

---

serve/serve.py

Add option to set document root via command line and overriding config. 
Reason for adding this option is following:
The ```merge_json``` method uses config.default.json keys which omit the ```doc_root``` option, 
so adding a ```doc_root``` option to an overriding config.json has no effect (i.e. the cwd is used).
Note: Changing merge_json would most probably cause more backward compatibility issues for others who potentially use the serve.py script in their integrations.
Also, by this option it's easier to reuse the existing wpt serve solution for integrating into the chromium blink test suite until we decide to support control on a lower level when configuring/starting/stopping the servers.
@jgraham

Serve: add doc_root option for overriding config.

---

serve/serve.py

Support data sharing between the main process and HTTP/S and WS/S servers.
Needs to land after this PR:  https://github.com/w3c/wptserve/pull/59/files
@jgraham, @mikewest

Stash: Basic support for shared data between processes

---

runner/index.html
runner/runner.js

Support multiple paths, separated by comma/space

---

serve/serve.py

This is used by wptrunner to dynamically construct the required routes
in particular for mount points other than /

Add a RoutesBuilder object to serve.

---

lint/lint.py

lint for usage of console.*

---

manifest/item.py
manifest/manifest.py
manifest/utils.py

This should fix most places which need path conversion from or to using the os path separator.

Fix more places need the path conversion

---

.gitmodules

The WebDriver specification tests will start using pytest soon.

Vendor pytest

---

.travis.yml
manifest/__init__.py
manifest/item.py
manifest/manifest.py
manifest/sourcefile.py
manifest/tree.py
manifest/update.py
manifest/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/65)

Test on python 3.

---

.travis.yml
runner/report.py
setup.cfg

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/66)

Add more testing.

---

lint/lint.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/68)

Refactor the lint whitelist handling.

---

.travis.yml
lint/__init__.py
lint/lint.py
lint/tests/test_lint.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/70)

Add a simple test for lint.

---

.travis.yml
lint/lint.py

This also disables the test for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/74)

Go back to importing localpaths at lint's top level.

---

runner/index.html
runner/runner.css
runner/runner.js

The format of the manifest had changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/67)

Fixed runner to handle references

---

lint/lint.py

This provides an interface for working with other tools; in particular
mozlint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/83)

Add json output to lint.

---

lint/lint.py
lint/tests/test_file_lints.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/94)

Refactor and test lint.

---

manifest/sourcefile.py
manifest/tests/test_manifest.py
manifest/tests/test_sourcefile.py
manifest/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/95)

Test SourceFile.

---

manifest/sourcefile.py
manifest/tests/test_sourcefile.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/100)

Test testharness test detection with various extensions.

---

lint/tests/test_path_lints.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/99)

Test the path lint.

---

lint/tests/test_file_lints.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/97)

Add a test for the open() mode lint.

---

lint/lint.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/98)

Remove unused set_type function.

---

tox.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/118)

Stop pip installing some dependencies.

---

manifest/sourcefile.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/132)

Fixing test URLs in manifest for worker tests

---

lint/lint.py
lint/tests/test_path_lints.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/141)

Add a lint for paths ending .worker.html

---

runner/runner.js
runner/update_manifest.py

Changes to update the test runner to support the new style manifest, resolves #144.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/147)

Manifest v4 change fixes

---

lint/lint.py
lint/tests/test_file_lints.py
lint/tests/test_lint.py
lint/tests/test_path_lints.py
manifest/tests/test_sourcefile.py

This currently only adds one; let's get this landed first before we start adding more complex and awkward lints with our current code!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/151)

CSS testsuite lints

---

sslutils/openssl.py

In the process of fixing a bug in this logic, I noticed an outstanding "to do" that was somewhat related, so I added a commit to address that, as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/165)

Improve certificate re-generation heuristic

---

manifest/sourcefile.py
manifest/tests/test_sourcefile.py
serve/serve.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/183)

Update support for generated tests (e.g. .any.html)

---

manifest/manifest.py
manifest/tests/test_manifest.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/195)

Add an iterator for all the tests from a filesystem path

---

lint/lint.py
lint/tests/test_lint.py
tox.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/190)

Markdown output for the lint
