serve/serve.py
Add support for running a WebSocket server over SSL (WSS).
@jgraham
=> WebSocket: Enable WSS support for web-platform-tests.

lint/lint.py
The canonical location of the WebIDL parser is /resources/WebIDLParser.js.
=> Check for webidl2.js references.

lint/lint.py
If the lint tool finds any errors, this causes it to emit a message with the Web URL for the lint-tool docs at https://github.com/w3c/web-platform-tests/blob/master/docs/lint-tool.md and to also emit a statement that it's sometimes OK to whitelist an error, and finally to emit a brief explanation of how to whitelist errors.
=> Make the lint tool emit a pointer to the docs.

runner/index.html, runner/runner.css, runner/runner.js
This commit adds collection of "NOT RUN" results to the test runner.
Sometimes this is the only appropriate result.  For example, Content Security Policy specifies certain behaviors around handling of plugin content.  If a user agent doesn't support that plugin / media type, the test doesn't pass or fail, it is just not run.  It may be that there is no way for a given user agent to support that plugin content (e.g. Flash with Safari for iOS) or it may be that additional configuration is required before a result can be obtained (e.g. installing Flash or Java plugins for Firefox).  Reporting the tests explicitly as NOT RUN gives an indication of this state that is more accurate than previous behavior of reporting such tests as failing.
=> update runner to display and report count of tests NOTRUN

runner/index.html, runner/runner.js
Simple filtering of displayed results by their outcome.
The filter is also being applied on-the-fly (as the test results are coming in.)
Few potential issues worth discussing:
* The test name DIV sometimes changes height if test name is too long (moves everything below it up'n'down)
* The summary should maybe be displayed before starting to run the tests (to be able to select filters)
* Download JSON results should maybe be renamed to "Download **all** results as JSON"
@jgraham
=> Add support for filtering displayed test results.

runner/index.html, runner/runner.js
PR introduces support for running tests under paths mathcing a regex.
The feature is optional (via a checkbox). 
**Example:**
```
/mixed-content/.*/websocket-request/.*
```
@jgraham 
CC: @mikewest
=> Implement support for filtering tests via regex.

manifest/item.py
This allows the same manifest to be updated on multiple
platforms without issue (e.g. for gecko which stores a
manifest in the source tree).
=> Ensure that MANIFEST.json always uses / as a path seperator.

manifest/manifest.py
Adding 'b' to the file mode ensures the file uses UNIX file format even on Windows.
Note that, this change isn't compatible with Python 3. In Python 3, we need to add `newline='\n'` instead of specifying binary mode.
=> Ensure that MANIFEST.json use UNIX file format.

manifest/manifest.py, manifest/tests/test_manifest.py
Previously we simply rewrote all the reftests in the local_changes section, leading to
huge and confusing diffs. Now instead store just a record of where tests are added
and where they have been removed.
=> Change the way that local changes to reftests are stored in the manifest.

manifest/sourcefile.py
Sourcefile.py was looking for html5lib, but did not know about
localpaths so was unable to resolve the import when called from the
command line in the top level WPT folder via the manifest python script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/69)
=> Fixed library search paths

lint/lint.py
Due to the way this code is used in web-platform-tests, the localpaths
import is required in that context, but not in tests in this repository.
This introduces the unfortunate problem that check_parsed() can only be
called through main(), but this is the fastest approach I can think of that
will allow the tests in this repository to keep working, while also
ensuring the lint script in web-platform-tests works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/73)
=> Delay the SourceFile import in lint.

sslutils/openssl.py
Use random starting certificate serial number on first run instead of a constant one. Switching between different local copies will no longer cause irrecoverable browser errors due to re-use of certificate serial numbers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/77)
=> Avoid duplicate certificate serial numbers

sslutils/openssl.py
OpenSSL requires that the serial number contain an even number of digits. The change in https://github.com/w3c/wpt-tools/commit/b388d6b14df8acc3fad070c74b435cd7aff056d1 did not maintain this property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/85)
=> Ensure serial number has even number of digits

runner/index.html, runner/runner.css
The logo was not floating left so the header text did not display in the
navbar (issue #80)
The manualUI block was too tall when running reftests.  This caused the
stop / pause buttons to be behind the dialog such that they could not be
selected without resizing the window (issue #78)
With these changes the UI header now looks like this:
and the reftest dialog looks like this:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/81)
=> Fixed logo and manual UI position

lint/lint.py, setup.cfg
Authors mistakenly using open() in text mode has caused a number of bugs
on Windows. It is rather hard to lint for correct usage here since
text-vs-binary is situation dependant. However it is quite possible to
lint that the author made some explicit choice in the subset of cases
where raw open() is called.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/87)
=> Add a lint to check that open() and file() calls in Python specify a mode.

__init__.py, lint/lint.py, manifest/sourcefile.py, manifest/update.py, serve/serve.py
This fixes ./manifest for people who don't have six installed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/112)
=> Import localpaths in __init__, avoiding the need to import elsewhere

manifest/sourcefile.py, manifest/tests/test_sourcefile.py
Manifest tool missed the `manual` in `mytest-manual.https.html` and thus incorrectly listed such tests in the automated section of the manifest file.
Commit includes regression test, although note I haven't managed to make pytest run on my computer for the time being. To be checked before merge!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/124)
=> Ensure manifest tool flags manual HTTPS tests as manual (#123)

manifest/sourcefile.py, manifest/tests/test_sourcefile.py, serve/serve.py
WebKit requires tests to finish with some specific prefixes.
Making this modification allows easier execution of *.any.js or *.worker.js tests in WebKit bots
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/126)
=> Ensure that any.js templated tests are finished by the .html suffix

serve/serve.py
This fixes a bug where even if bind_hostname is set to False the StashServer would still attempt to bind to the hostname.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/143)
=> Don't bind StashServer to host name if bind_hostname is false.

manifest/log.py
This function call has global side-effects on the `logging` module and
is therefor inappropriate for use within utility code.
> ### `logging.basicConfig([**kwargs])`
>
> Does basic configuration for the logging system by creating a
> `StreamHandler` with a default `Formatter` and adding it to the root
> logger. The functions `debug()`, `info()`, `warning(`), `error()` and
> `critical()` will call `basicConfig()` automatically if no handlers
> are defined for the root logger.
source: https://docs.python.org/2/library/logging.html#logging.basicConfig
This should resolve https://github.com/w3c/web-platform-tests/issues/4323
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/155)
=> Remove "basic" logging configuration

runner/runner.js
We can only open new windows in response to a click, so do that even if
we first have to load the manifest.
Also reset the window when we close it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/164)
=> Avoid hitting chrome's popup blocker

serve/serve.py
This ensures that optional command-line arguments like `--latency` are
available when specified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/166)
=> [wptserve] Forward keyword args to spawned process

runner/index.html, runner/runner.css, runner/runner.js
While running tests, the runner communicates its status via a dynamic
"progress" indicator. During "steady" states such as "testing stopped," and
"testing complete," the concept of "progress" does not apply. In these cases,
the "progress" indicator is re-used to simply display a static text value.
The "test manifest generation" state is another example of a "steady" state.
Prior to this patch, however, it was communicated via a dedicated UI element.
This inconsistency limited the authority of the progress indicator--users
needed to consult two independent UI elements to determine the status of the
test runner.
Re-use the existing convention for "steady" states to communicate when the
application is generating the test manifest. Increase visibility by rendering
the element in this state …
=> Runner: Improve UI during manifest generation

lint/lint.py, manifest/item.py, manifest/sourcefile.py, manifest/tests/test_sourcefile.py
Use a syntax like in worker tests i.e.
```
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/wpt-tools/172)
=> Support long timeouts in WebDriver tests.
